CREATE DATABASE IF NOT EXISTS login;
USE login;
CREATE TABLE IF NOT EXISTS login.member (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  username VARCHAR(30) NOT NULL, 
  password CHAR(128) NOT NULL, 
  salt CHAR(128) NOT NULL
) ENGINE = InnoDB;